---

- name: create namespace to deploy central
  ansible.builtin.shell:
    cmd: oc new-project "{{ centralNamespace }}"
  ignore_errors: yes

- name: create yaml to deploy central
  ansible.builtin.template:
    src: central.yaml.j2
    dest: "{{ centralYaml }}"
    mode: '0644'

# this is needed for some red hat labs which has this configured
- name: delete limits in the central namespace
  ansible.builtin.shell:
    cmd: oc delete limitrange -n "{{ centralNamespace }} {{ centralNamespace }}-core-resource-limits"
  ignore_errors: yes 
  retries: "{{ numRetries }}"
  delay: "{{ delayTime }}"

- name: deploy central
  ansible.builtin.shell:
    cmd:  oc apply -f "{{ centralYaml }}" -n "{{ centralNamespace }}"
  retries: "{{ numRetries }}"
  delay: "{{ delayTime }}"
  register: result
  until: result.rc == 0
