---

- name: create namespace to deploy central
  ansible.builtin.shell:
    cmd: oc new-project "{{ centralNamespace }}"
  ignore_errors: yes

- name: create yaml to deploy central
  ansible.builtin.template:
    src: central.yaml.j2
    dest: "{{ centralYaml }}"
    mode: '0644'

# this is needed for some red hat labs which has this configured
- name: delete limits in the central namespace
  ansible.builtin.shell:
    cmd: oc delete limitrange -n "{{ centralNamespace }} {{ centralNamespace }}-core-resource-limits"
  ignore_errors: yes 
  retries: "{{ numRetries }}"
  delay: "{{ delayTime }}"

- name: deploy central
  ansible.builtin.shell:
    cmd: oc apply -f "{{ centralYaml }}" -n "{{ centralNamespace }}"

- name: get central password
  ansible.builtin.shell:
    cmd: oc -n "{{ centralNamespace }}" get secret central-htpasswd -o jsonpath="{.data['password']}" | base64 -d
  register: centralPass
  ignore_errors: yes 
  retries: "{{ numRetries }}"
  delay: "{{ delayTime }}"

- name: get central url
  ansible.builtin.shell:
    cmd: oc -n "{{ centralNamespace }}" get routes/central -o jsonpath='{.spec.host}'
  register: centralUrl
  ignore_errors: yes 
  retries: "{{ numRetries }}"
  delay: "{{ delayTime }}"
  
- name: setting var to store admin password
  ansible.builtin.set_fact:
    acsAdminPass: "{{ centralPass.stdout }}"

- name: setting var to store acs's console url
  ansible.builtin.set_fact:
    acsUrl: "{{ centralUrl.stdout_lines[0] }}"

- name: print central connection data on stdout
  debug:
    msg: "Central password for admin user: {{ acsAdminPass }} ACS console: https://{{ acsUrl }}"