---

- name: download roxcli
  ansible.builtin.get_url:
    url: "{{ roxcliUrl }}"
    dest: "{{ roxctlCmd }}"
    mode: '0755'

- name: add cluster to acs
  ansible.builtin.shell:
    cmd: roxctl -e "{{ acsUrl }}" central init-bundles generate acsdemo --insecure-skip-tls-verify --output-secrets "{{ bundleYaml }}" --password "{{ acsAdminPass }}"