---

- name: download roxcli
  ansible.builtin.get_url:
    url: "{{ roxcliUrl }}"
    dest: "{{ roxctlCmd }}"
    mode: '0755'

- name: create init bundle
  ansible.builtin.shell:
    cmd: /tmp/roxctl -e "{{ acsUrl }}":443 central init-bundles generate "{{ clusterName }}" --insecure-skip-tls-verify --output-secrets "{{ bundleYaml }}" --password "{{ acsAdminPass }}"

- name: apply init bundle
  ansible.builtin.shell:
    cmd: oc -n "{{ centralNamespace }}" apply -f "{{ bundleYaml }}"

- name: create yaml to add secure cluster
  ansible.builtin.template:
    src: securecluster.yaml.j2
    dest: "{{ secureClusterYaml }}"
    mode: '0644'

- name: add secure cluster
  ansible.builtin.shell:
    cmd: oc -n "{{ centralNamespace }}" apply -f "{{ secureClusterYaml }}"
